### ISSUE TITLE
Error:"format_bp" 

### ISSUE THREAD

**Issue by brooksph** [dib-lab/sourmash#383]
I can confirm that the "notify" error is resolved but a new error popped up.

Traceback (most recent call last):
File "/home/ubuntu/.local/bin/sourmash", line 9, in 
load_entry_point('sourmash==2.0.0a2', 'console_scripts', 'sourmash')()
File "/home/ubuntu/.local/lib/python2.7/site-packages/sourmash_lib/main.py", line 63, in main
cmd(sys.argv[2:])
File "/home/ubuntu/.local/lib/python2.7/site-packages/sourmash_lib/commands.py", line 927, in gather
args.threshold_bp):
File "/home/ubuntu/.local/lib/python2.7/site-packages/sourmash_lib/search.py", line 147, in gather_databases
format_bp(intersect_bp))
NameError: global name 'format_bp' is not defined

**Comment by ctb** [comment]
This is fixed in #380.

**Comment by mherold1** [comment]
I still have the error as well:
```
loaded query: mags/D13_G1.3.2.fa... (k=31, DNA)
loaded 0 signatures and 1 databases total.
Traceback (most recent call last):
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/sourmash_venv/bin/sourmash", line 11, in <module>
    load_entry_point('sourmash==2.0.0a2', 'console_scripts', 'sourmash')()
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.5.3/envs/sourmash_venv/lib/python3.5/site-packages/sourmash_lib/__main__.py", line 63, in main
    cmd(sys.argv[2:])
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.5.3/envs/sourmash_venv/lib/python3.5/site-packages/sourmash_lib/commands.py", line 927, in gather
    args.threshold_bp):
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/pyenv/versions/3.5.3/envs/sourmash_venv/lib/python3.5/site-packages/sourmash_lib/search.py", line 147, in gather_databases
    format_bp(intersect_bp))
NameError: name 'format_bp' is not defined
```
before I tried upgrading the sourmash installation with:
`pip install -U git+https://github.com/dib-lab/sourmash@master` : 
```
  Found existing installation: sourmash 2.0.0a2
    Uninstalling sourmash-2.0.0a2:
      Successfully uninstalled sourmash-2.0.0a2
  Running setup.py install for sourmash ... done
Successfully installed sourmash-2.0.0a2
```
any chance I have to install in a different way to have the fixed version? However, before upgrading I had a similar error with "notify".

**Comment by brooksph** [comment]
Hi @mherold1. This error is fixed on the `fix/sbt_search` branch and but hasn't been merged into master yet. You can grab that branch using `git clone -b fix/sbt_search https://github.com/dib-lab/sourmash.git`. It might be different on your system but on a clean ubuntu 16.04 the following works for me. 

#### Update packages and install virtual env
    sudo apt-get update
    sudo apt-get install -y python3.5-dev python3.5-venv make \
    libc6-dev g++ zlib1g-dev

#### Create and activate a python virtual env
    python3.5 -m venv ~/py3
    . ~/py3/bin/activate

#### Install sourmash dependencies 
    pip install -U pip
    pip install -U Cython
    pip install -U jupyter jupyter_client ipython pandas matplotlib scipy scikit-learn khmer ijson

#### Clone sourmash branch with fix (fix/sbt_search)
    git clone -b fix/sbt_search https://github.com/dib-lab/sourmash.git
    cd ~/sourmash
    make 
    cd

**Comment by nick-youngblut** [comment]
Any idea on when this bug will be fixed in the bioconda version of sourmash? Currently, bioconda has 2.0.0a2 available for linux. This notify bug is a pain to work around when trying to integrate sourmash into snakemake pipelines. I guess I should probably just bug the bioconda developers...

**Comment by luizirber** [comment]
@nick-youngblut version updated to `2.0.0a3` on bioconda, I'm closing this issue since it is solved now.
